### ISSUE TITLE
Can't add any of the white digimon cards from EX2 into deckbuilder

### ISSUE THREAD

**Issue by tari101190** [TakaOtaku/Digimon-Card-App#10]
Can't add any of the white digimon cards from EX2 into deckbuilder.
I can only add the white Digi-Egg, and the white Option.
Also I should be able to add up to 50x of EX2-046 to the deck.

![image](https://user-images.githubusercontent.com/104586582/166627873-64f77340-7655-4c9d-82ca-3557a7c27f65.png)

**Comment by ChristianCodeCamp** [comment]
Fixed!
