### ISSUE TITLE
Edit the Japanese ST12-13's name to Sistermon Noir. And it's Attribute to Virus.

### ISSUE THREAD

**Issue by tari101190** [TakaOtaku/Digimon-Card-App#11]
Please manually edit the Japanese version of ST12-13's name to Sistermon Noir. And it's Attribute to Virus.

![image](https://user-images.githubusercontent.com/104586582/166630396-3c7de881-0113-46e6-92ed-8f93961bea3b.png)

**Comment by ChristianCodeCamp** [comment]
Fixed!
