### ISSUE TITLE
can't add multicolour digimon to decks in deckbuilder

### ISSUE THREAD

**Issue by tari101190** [TakaOtaku/Digimon-Card-App#141]
can't add multicolour digimon to decks in deckbuilder

**Comment by TakaOtaku** [comment]
![image](https://user-images.githubusercontent.com/9803280/169405274-03dcd603-78c2-459d-89aa-592971b8c6d2.png)
Doesnt seem to be a problem

**Comment by tari101190** [comment]
it's not working for me. they aren't adding to the deck at all.
