### ISSUE TITLE
Adjustments not saving

### ISSUE THREAD

**Issue by FhtagnDazs** [TakaOtaku/Digimon-Card-App#293]
Adjustment to card collection numbers are not saving unless I click one of the adjustment buttons again. If I use the arrows, I must then click the plus or minus button or it will not save. If I click the down arrow, the number goes immediately to zero and saves immediately, however. If I use the plus and minus buttons, the first click increases the number but it doesn't save unless I click one of the plus or minus buttons again, which has no effect on the number but seems to save the current number. This means increasing by the plus or minus buttons involves clicking the buttons twice as many times as necessary. Also, If the number is at 1 and I click the minus to reduce it, I am unable to click the minus again to save (presumably because the minus button is not supposed to be doing anything since the amount is already at 0) and I must click the plus button to save it.

**Comment by TakaOtaku** [comment]
Already fixed it yesterday :) 
Reducing Count with the arrow keys should not work, but I may look into adding it :)
