### ISSUE TITLE
[Proposal] Refactor the Sort to Maintain Original Card IDs

### ISSUE THREAD

**Issue by hipsterk** [TakaOtaku/Digimon-Card-App#3]
This refactor will revert Starter Deck IDs to `STX-` instead of `ST0X-` allowing for those cards to be searched properly by their IDs, i.e., searching `ST1-07` to find Greymon, instead of searching `ST01-07` like on the live site. I've noticed that the Starter Deck IDs were modified in order to properly sort `ST10` after `ST2` instead of before `ST2` in 1325bf754e109eff1466dfeca2881dd9d65495e5, so I think that this refactor would be beneficial to implement as `BT10` is coming and that would be sorted incorrectly in the same fashion.

Minor changes that I would also be adding would be cleaning up some of the incorrect values in the [english.json](https://github.com/TakaOtaku/Digimon-Card-App/blob/d3660a8/src/assets/cardlists/english.json) and [japanese.json](https://github.com/TakaOtaku/Digimon-Card-App/blob/d3660a8/src/assets/cardlists/japanese.json).

I may also set the Level and DP sort buttons to toggle on the Digimon Card Type filters as a user that is trying to sort by either of those metrics probably wouldn't want to see Tamers or Options.

I have a basic version of the implementation on the `refactor-sort` branch of my fork, but want approval/feedback before I continue development regarding these changes.

**Comment by TakaOtaku** [comment]
That looks good to me! 
I didn't know you could set localCompare to numeric and that it would work on strings that contain numbers and symbols like "ST1-01". So if the sorting is correct, we can do it like this. There are a few places were I put workarounds because of this (export dialog, import dialog, and generell id-compare) which can be removed as well :).

**Comment by TakaOtaku** [comment]
Also you could just create a branch in this repo, that would be easier to view for me. 
Or would you need to be a collaborator to create branches?

**Comment by TakaOtaku** [comment]
Did push the changes you made because I had the time :)
