### ISSUE TITLE
In Deckbuilding, please treat multicoloured cards as their left-side colour instead.

### ISSUE THREAD

**Issue by tari101190** [TakaOtaku/Digimon-Card-App#302]
In deckbuilding, please make multicoloured cards be treated primarily as their colour on the left rather than a 7th colour category of multicolour.

![image](https://user-images.githubusercontent.com/104586582/175888299-0a1140d4-e3a8-41c4-bf03-1e3d727a791e.png)

**Comment by TakaOtaku** [comment]
Completed!
