### ISSUE TITLE
Deck image generation glitch

### ISSUE THREAD

**Issue by herculess89** [TakaOtaku/Digimon-Card-App#303]
When generating deck image (TTS) there is a glitch with numbers on the first card
![Untitled](https://user-images.githubusercontent.com/86571930/176042967-000a4750-bbac-401f-850d-261e27e742ec.jpg)
.

**Comment by TakaOtaku** [comment]
Hmm thats weird, it probably happens when the browser doesnt have enough time to generate the image I will look into it.
Sorry for the long delay.

**Comment by TakaOtaku** [comment]
Can't seem to reproduce it. When the internet is slow, it can take a few seconds to generate the image, though.
If you can reproduce it, please let me know :)

**Comment by herculess89** [comment]
I am using the Brave browser so that could be the reason. Also i tried on Firefox and it doesn't download the image at all.
