### ISSUE TITLE
Feature Request: Filter by Collection

### ISSUE THREAD

**Issue by gbh101** [TakaOtaku/Digimon-Card-App#309]
The ability to filter so that only cards that are in the user's collection are visible would be handy for building decks out of only cards that a user owns.

**Comment by TakaOtaku** [comment]
You can just increase the number of cards filter for that :)
![image](https://user-images.githubusercontent.com/9803280/176991737-26836e12-f545-4a29-b402-94d2b4018327.png)
Set it to 1 and you get all cards you have at least once
