### ISSUE TITLE
Feature Request: Separate Collection Builder/Viewer and Deck Building pages

### ISSUE THREAD

**Issue by gbh101** [TakaOtaku/Digimon-Card-App#310]
It would be handy if a user could have a separate page for editing their collection, where they don't have to worry about accidently putting cards into a deck. It would also be nice if collection mode didn't make card that aren't owned greyscale as it can be hard to identify cards based on image in greyscale.

**Comment by TakaOtaku** [comment]
The first thing is in the works, the second thing can be changed. 
You can go to the Settings and set the Cards you want to collect to 0, then every card that has at least 0 will be in color.
