### ISSUE TITLE
Feature Request: Scalable Card Images

### ISSUE THREAD

**Issue by gbh101** [TakaOtaku/Digimon-Card-App#311]
It would be great to be able to scale the card images up and down in both the "Deck View" and the "Card View."

**Comment by TakaOtaku** [comment]
I try to add something of the sort, but there are a few technical problems with this one, so it will probably take a while.

**Comment by lupoDharkael** [comment]
I'd like to add some feedback here, I've shown digimoncard.app to some friends and more than one tried to used the page zoom feature from the browser while using the web. 
Some of them frequently tried to zoom just to see deck better with the Deck View open and the Card View closed. When you change the page size the Card view opens each time you change the zoom level. Even if card zoom is hard to implement it would make it less frustrating for some users if the hidden status of the page components would be preserved after a zoom level change.

**Comment by TakaOtaku** [comment]
I get that, but I'll tried implementing it a few times, but always broke something on some resolutions... 
Of course, I haven't given up yet
