### ISSUE TITLE
Feature Request: Independently Scrolling "Card View" with Unlimited Cards

### ISSUE THREAD

**Issue by gbh101** [TakaOtaku/Digimon-Card-App#312]
It would be nice if the user could scroll the "Card View" without scrolling the whole page as well as being able to increase the maximum number of displayed cards in the "Card View" to minimize the number of pages (or allow all cards to be on a single scrolling page).

**Comment by TakaOtaku** [comment]
That is something which I had at the beginning and would add again if I would have more funding, or a sponsor :) 
95% of the server cost is coming from loading images for the users, so I try to keep the cards that are loaded to a minimum.

When the current user-pool grows and the site has a bigger audience cardmarket considers sponsoring the site, then i can add this.
