### ISSUE TITLE
Bug: Creating a New Deck from the Deckbuilder toolbar overwrites the previous deck that was being worked on.

### ISSUE THREAD

**Issue by gbh101** [TakaOtaku/Digimon-Card-App#313]
It would be great to have the "New Deck" button be at the top of the page at all times, instead of only on the "My Decks" page.

**Comment by TakaOtaku** [comment]
You also have a button for new Decks in the Deckbuilder-toolbar :)
![image](https://user-images.githubusercontent.com/9803280/176845348-b1a240a3-a0cc-4726-92e7-a7815cb4a728.png)

**Comment by gbh101** [comment]
Actually, renaming this to a bug, as I just tried to build a deck, saved it, then selected New Deck using the method shown and it overwrote the deck I had made.

**Comment by gbh101** [comment]
Bug Repro Steps:

- Add cards to a deck
- Name and save the deck
- Click "New Deck" and confirm
- Add cards to the new deck
- Name and save the new deck with a different name
- Go to My Decks page and see that only the second deck exists

Expected Outcome:
2 decks exist, one with the first name and contents and one with the second name and contents.

**Comment by TakaOtaku** [comment]
Should be fixed
