### ISSUE TITLE
Bug: EX3-061 Dinobeemon card text wrong.

### ISSUE THREAD

**Issue by Kawsmecal** [TakaOtaku/Digimon-Card-App#360]
**Listed effect is:** 
[When Digivolving] When DNA digivolving, you may play 1 [Dinobeemon] from your trash without paying the cost.
[On Deletion] You may play 1 [Veemon] from your trash without paying the cost.

**Actual effect is:** 
[When Digivolving] When DNA digivolving, you may play 1 [Paildramon]  from your trash without paying the cost. 
[On Deletion] You may play 1 [Wormmon] from your trash without paying the cost.

**Comment by TakaOtaku** [comment]
Fixed with the next Update Thank you!
