### ISSUE TITLE
[Feature Request] Change digimon level slider to buttons instead

### ISSUE THREAD

**Issue by Lys8426** [TakaOtaku/Digimon-Card-App#364]
This would make it much easier to search for just 1 level of digimon. Having to adjust the slider to 4-4 for example is a bit messy.

This is a great tool! Thank you so much for your hard work!

**Comment by TakaOtaku** [comment]
Yeah I think this would be better :) I do kinda like the sliders, but they aren't implemented the best so they should go :) Gonna include it in the next Update soon :)
