### ISSUE TITLE
Too Many Unique Cards Can Overflow The Deck Menu

### ISSUE THREAD

**Issue by DarkRuler17** [TakaOtaku/Digimon-Card-App#390]
When over 32 unique cards are selected in a deck, cards begin to go off screen with no scroll wheel option.
![image](https://user-images.githubusercontent.com/113749644/190840390-c196b1c8-e8eb-4012-ac41-4924fa9be231.png)

**Comment by TakaOtaku** [comment]
Will probably not happen with most decks, but if one wants to play another format it is bad. Working on it
