### ISSUE TITLE
[Feature Request] Collection only workspace

### ISSUE THREAD

**Issue by Caraminyu** [TakaOtaku/Digimon-Card-App#396]
I often just want to see my collection as it is without all the cards I don't have in the middle.
It'd also be helpful if I were to a build deck with cards in my collection but the current display is discouraging in that regard.

**Comment by TakaOtaku** [comment]
I do have a to-do already to make a site for just the collection view, separate from the deck-builder altogether.

The second one should be pretty easy to do, you can set the slider for cards to at-least one.
![image](https://user-images.githubusercontent.com/9803280/192497361-af5532a3-8335-49c6-a3ed-3c99edc87981.png)
Not that it would stop you from using cards you don't have. That would be a feature I can put in my todo.

**Comment by Caraminyu** [comment]
Ah, sorry, it must have slipped from my view. //
Also, smart idea, I didn't realize I could do that.
SInce it's already in your to-do I'll close it here.
