### ISSUE TITLE
Bug: You can't add 5+ cards to the deck

### ISSUE THREAD

**Issue by juansolobolos** [TakaOtaku/Digimon-Card-App#400]
I know its made to make all decks legal but now you cant build eosmons/dReaper decks.

**Comment by TakaOtaku** [comment]
![Screenshot_20221005-221823](https://user-images.githubusercontent.com/9803280/194155155-5fe7efa3-a47c-47b4-9d23-e68b19a15a0a.png)
You can add them.

**Comment by juansolobolos** [comment]
well. i tried now and i can. idk why but i tried to add them this afternoon and i couldnt add more than 4. weird...
