### ISSUE TITLE
[Feature Request] Show what cards of the deck are you missing in your collection

### ISSUE THREAD

**Issue by juansolobolos** [TakaOtaku/Digimon-Card-App#401]
A lot of times i watch a deck and i wonder what cards of it i have and what i dont. it would be cool to have a filter to show only the cards currently in the deck and all their versions

**Comment by TakaOtaku** [comment]
The X Button in the Deck view Shows the missing Cards, but it is broken in the current Update.

**Comment by juansolobolos** [comment]
ok. Nice to know that its going to come in the future

**Comment by TakaOtaku** [comment]
Should work since quite a while ago, I just forgot to close the thread.
