### ISSUE TITLE
[Feature Request] More advance options for collection stats

### ISSUE THREAD

**Issue by juansolobolos** [TakaOtaku/Digimon-Card-App#402]
I think it would be nice to add the posibility of desactivate pre release, stamped, and alter arts for your collection stats (the four wheels). For example maybe i dont like pre release cards and i prefer to dont have them missing in my collection stats.

**Comment by TakaOtaku** [comment]
You can set some in the settings, those reflect in the pie charts.
But Yeah they are pretty lackluster right not.
