### ISSUE TITLE
Can't open saved decks from Profile tab on mobile

### ISSUE THREAD

**Issue by RickSneeze** [TakaOtaku/Digimon-Card-App#404]
Need to add a long press or double tab function in order to open saved decks from Profile tab because you can't right click on mobile

**Comment by TakaOtaku** [comment]
You should be able to do both actually.
I tried them on my phone right now 🤔
I know that, Apple sometimes makes trouble, which phone and Browser do you use?

**Comment by RickSneeze** [comment]
iPhone 8 Plus. Tried on both Safari and Chrome and I can't get it to open

**Comment by TakaOtaku** [comment]
You can now click on the name of the deck, this opens the context menu :)
