### ISSUE TITLE
Show more button blocked

### ISSUE THREAD

**Issue by EastML** [TakaOtaku/Digimon-Card-App#423]
The show more button cannot be seen. The chrome menus block it. I’m not sure if this is an iOS device issue or a chrome issue. 

The second image is when I pull the page with my thumb and take a snapshot. 

Final image is the problem in landscape mode.

Device: iPhone 12 Pro
OS: 16.0
Browser: Chrome

![ECD390D2-6B86-4662-8716-15152B41D99F](https://user-images.githubusercontent.com/13641665/196038460-78fdcfaf-224a-4510-bc30-5c86ce3c873b.png)
![AE754310-5015-4AC2-BB8C-30DE58EDFAA9](https://user-images.githubusercontent.com/13641665/196038463-57fe0d9d-c161-48a4-89ca-95b5d863830b.png)
![12414D34-668C-4FBE-988B-E47A37BC107E](https://user-images.githubusercontent.com/13641665/196038464-f77f557c-723c-41e2-91c9-fed575d7bd8c.png)

**Comment by TakaOtaku** [comment]
Ohh that is a app breaking bug. I try to fix it in a moment.

**Comment by TakaOtaku** [comment]
It should show now, but I am not sure what changed for that to happen.
I have to look into it more later on :)

**Comment by EastML** [comment]
I can confirm the issue has been resolved on landscape, but on portrait on mobile devices the problem still persists. Images below:

 
![2763B9F4-E284-474E-A12C-7796020EE3E8](https://user-images.githubusercontent.com/13641665/196115204-7c7715c1-8d74-4359-ab7c-0e3dbf55b0db.png)

![9BA32F1F-C2BD-4C39-9124-F7DDFCC6C009](https://user-images.githubusercontent.com/13641665/196115248-7f4a9b2c-9d12-463d-9980-e86d0a3ea36e.png)
