### ISSUE TITLE
Mobile search bar could be improved

### ISSUE THREAD

**Issue by EastML** [TakaOtaku/Digimon-Card-App#424]
Low Priority but the search bar, filter button, and collection mode would be a bit nicer on mobile if they were full width each and stacked  column-wise

**Comment by TakaOtaku** [comment]
That is absolutly correct, I didn't think of that! Gonna do that soon!

**Comment by TakaOtaku** [comment]
I now moved Collection Mode down one row, but i left filter and search in one row.
