### ISSUE TITLE
Rules section and card Q&A

### ISSUE THREAD

**Issue by EastML** [TakaOtaku/Digimon-Card-App#425]
Would be nice if there was a section on rules Where you could search card rulings based on card number or name, and link to card ruling for a specific card in its details

**Comment by TakaOtaku** [comment]
There is in a way, when you view a card, there is a "?" beside the name, which will get you to the wiki where all rulings and everything is documented.

But I could try to grab it with my python scripts sometime in the future and put it somewhere on my site.
