### ISSUE TITLE
Export all doesn't work

### ISSUE THREAD

**Issue by ycdevbdsp** [TakaOtaku/Digimon-Card-App#434]
I was poking around hoping for an export capability and really excited that there seems to be one, but nothing happened when I clicked it.  The page says to not select any sets if you want to export your entire collection, so that's what I tried to do. Console log says "this.sets is undefined".

I tried selecting just BT10 and the export worked.

**Comment by TakaOtaku** [comment]
Yeah its a bit unintuitiv maybe. You only export what you have selected at the moment. I will change it to, when you have nothing selected you export everything.

**Comment by TakaOtaku** [comment]
Should already work as intended now :)
