### ISSUE TITLE
BT1-012 Biyomon Incorrect Illustrator

### ISSUE THREAD

**Issue by zenturion89** [TakaOtaku/Digimon-Card-App#442]
BT1-012 Biyomon's illustrator is listed as KISUKE but it should be TANIMESO. I did notice that the wiki has this mistake as well so if you pulled the info from the wiki this is likely where this came from.

![image](https://user-images.githubusercontent.com/38173837/199813574-8441d169-055d-4423-9cdb-d45d69ca07ce.png)

**Comment by TakaOtaku** [comment]
Ohh thanks I fixed it! :)
