### ISSUE TITLE
Exports not entirely working correctly.

### ISSUE THREAD

**Issue by AquaLavena** [TakaOtaku/Digimon-Card-App#444]
I noticed two issues while messing with exporting the collection today.

1. Adding a card to a collection then removing it, (Collection count 0 then to 1 then back to 0) will still show the card in your exported list of cards in your collection despite it being 0. Not major as it is still listed as 0 on the txt doc. Players can accidentally add a card then remove it or trade/sell cards from their collection bringing it back to 0.

2. Exports are missing some cards. I selected BT1 for the set, all rarities, and all versions. Then I exported my collected cards and exported my missing cards at a goal of 1 each. Somehow both list were missing cards.

Missing card list sample:
id,count
"BT1-001",1
"BT1-003",1
"BT1-003_P1",1
"BT1-007",1
"BT1-009",1
"BT1-010",1
"BT1-010_P1",1
"BT1-010_P2",1
"BT1-010_P3",1

Obtained card list sample:
count,id
0,"BT1-001"
0,"BT1-003_P1"
1,"BT1-006"
4,"BT1-009_P1"

002, 004, 005, 008 are all missing. I don't have those cards in my collection so they should be in the missing card list. There are several other missing cards through out the exports so not sure what is happening with them

**Comment by TakaOtaku** [comment]
Yeah the first one should not add it to the .txt, as a card with 0 you don't really have.

As for the second one, I will try to look into it, what went wrong.

**Comment by TakaOtaku** [comment]
Should work with the next update :)
