### ISSUE TITLE
Imperialdramon: Dragon Mode BT3-111 Draconic Roar (ex3) version missing

### ISSUE THREAD

**Issue by Caraminyu** [TakaOtaku/Digimon-Card-App#448]
This one doesn't appear when I search : https://www.cardmarket.com/fr/Digimon/Products/Singles/Draconic-Roar/Imperialdramon-Dragon-Mode-BT3-111
I assume you've forgotten to add it since the rest of ex3 is on the website.

**Comment by TakaOtaku** [comment]
Fxed with the next update, thank you!
