### ISSUE TITLE
[Minor Bug]Removing cards from deck doesnt reflect on the collection list at first

### ISSUE THREAD

**Issue by Lumase1996** [TakaOtaku/Digimon-Card-App#450]
Removing cards from a deck doesnt update the collection and the copies actually being used, only adding cards updates the collection.
For example:
- i added 2 plesiomon from ex3 to a deck, so on the collection it shows 2 copies being used currently
- i removed 1 copy of it from the deck but on the collection it still appeared as 2 copies being used
- i added another card to the deck and then the collection updated, showing only 1 copy of plesiomon as it should be.

here is a picture of what i meant:
![visual bug](https://user-images.githubusercontent.com/114258661/206206017-d5aa05c2-68f3-4480-81ff-39b586390315.jpg)

**Comment by TakaOtaku** [comment]
Gonna take a look at it :)

**Comment by TakaOtaku** [comment]
Should be fixed!
