### ISSUE TITLE
[Bug] Profile failing to load and be interactable when decks fail to load correctly

### ISSUE THREAD

**Issue by GavinMarkee** [TakaOtaku/Digimon-Card-App#452]
After logging in post the new UI update (07.12.2022) and attempting to load my profile page, the entire site locks up except for using the logo to return to the homepage, and the dropdown menu if it is already open. Image attached of chrome's developer console on the page.
![profile page](https://user-images.githubusercontent.com/5481120/207634730-b0745e58-150b-4024-bd0d-26a45dd0adb3.png)

**Comment by TakaOtaku** [comment]
Ohh sorry for the bug, could you send me your profile link.
I have an idea what the reason is and will deploy a fix today

**Comment by GavinMarkee** [comment]
Sure thing, it's: https://digimoncard.app/user/G7Xu3RXhBfgp9Er0m3I5nOp9nI92

**Comment by GavinMarkee** [comment]
Thank you, looks like everything is working great!
