### ISSUE TITLE
EX4 Pinamon is classified as a Digimon rather than an egg and cannot be added to the deck.

### ISSUE THREAD

**Issue by dp101428** [TakaOtaku/Digimon-Card-App#453]
In searches, if I search for eggs EX4 Pinamon doesn't show up, and if I search for Digimon, it does. Furthermore, whenever I attempt to add a Pinamon to my decklist, the number of eggs remains at 0, and no copies show up on the left. The card browser shows a 1/4 on Pinamon (though I've observed that count being inaccurate before) but clicking it additional times does nothing. I tried multiple other purple eggs and multiple other EX4 eggs and all of them worked, tried reloading the page, making a new deck, importing a decklist with Pinamon already in it, and none of those methods worked. Despite the above issues of it being classified as a digimon rather than an egg, it doesn't increment the counter of digimon either.

**Comment by TakaOtaku** [comment]
Yeah that was my mistake. I fixed it and it should be live in a few minutes. Sorry for the late response :)
