### ISSUE TITLE
UX Feedback: Add ability to select number of cards per page

### ISSUE THREAD

**Issue by dartanian300** [TakaOtaku/Digimon-Card-App#455]
This feedback is relevant to card list views on desktop.

From a UX perspective, it is a little annoying to have to scroll to the top of the page and change the page (pagination) constantly. It would be useful if we as users could change the number of cards shown per page so we don't have to scroll to the top of the page as often.

Additionally, adding the pagination to the bottom of the page as well would be very useful.

**Comment by TakaOtaku** [comment]
I did have an ability to choose how many cards should be displayed once, but nobody seemed to like it, so I kicked it.
I would love to implement it so, that the cards get scaled, so you don't have to scroll, but I always run into some kind of problems when trying to do that, unfortunately.

**Comment by dartanian300** [comment]
I like the idea of the cards scaling but I think that may introduce some odd sizes for different devices. Would you be opposed to bringing back the option to select number of cards on the page?

**Comment by TakaOtaku** [comment]
If you can find a place where it finds, sure :)

**Comment by TakaOtaku** [comment]
Will be irrelevant with the next update as card scaling is coming.
