### ISSUE TITLE
UX Feedback: Collection mode hard to see

### ISSUE THREAD

**Issue by dartanian300** [TakaOtaku/Digimon-Card-App#457]
This feedback refers to the card list collection mode.

When entering collection mode all cards are turned black and white. This makes it fairly difficult to find the card you're looking for (especially if the screen has multiple cards with busy art on them). Additionally, due to the +/- buttons, some card's names are covered which makes it even harder to find the card.

Perhaps instead of making cards grayscale you could drop the opacity of the cards not in the collection. That would go a long way in helping to easily find the correct card without using the search bar. If you wanted to take it a step further you could move the +/- buttons below the card so none of the card text is covered.

Another option is to add the card's number somewhere as regular text so it's easier to see than squinting at the number that's printed on the card.
<img width="1964" alt="Screen Shot 2023-01-03 at 10 57 23 AM-min" src="https://user-images.githubusercontent.com/3358537/210393933-c18f67a7-1d78-4dcd-9814-a65c2df2d52a.png">

**Comment by TakaOtaku** [comment]
You could change in the setting that you don't want to show cards as grayscale.
I didn't try out the opacity one yet, so I will try out how this would look like. 

At the start I had the -/+ below the cards and I got quite a few messages, of people who didn't like the wasted space. 
Not really sure what would really be better.

Thanks for the feedback btw!

**Comment by dartanian300** [comment]
Ah, didn't know about the grayscale setting. Thanks!

After using the app quite a bit more yesterday I believe the biggest issue is when you can't see the card name (rather than it being black and white). That issue is compounded for level 6/7 cards because they usually don't have inherited effects and thus their names are covered (and these are usually the busiest cards).

What if, for desktop, you hide the +/- buttons until someone hovers over the card. For the number of cards in the collection, leave that up but give the background some transparency. You may be able to read the card names in that case.

Now that I've got the dev environment setup I may play with this myself and see if I can come up with any solutions.

**Comment by TakaOtaku** [comment]
I am gonna play around with it and see if it looks good :) 
Gonna look forward to your solution as well :)
