### ISSUE TITLE
UX Feedback: Don't allow multiple modals to open at the same time

### ISSUE THREAD

**Issue by dartanian300** [TakaOtaku/Digimon-Card-App#459]
Currently, it's possible to open multiple modals by clicking on cards that are behind an open modal. This can be a very confusing experience for users. 

One solution would be to add a `div` behind the modal that darkens the background. This would prevent users from being able to click a card while a modal is open. Additionally, clicking the darkened background could close the modal which would be a nice feature since the only way to close it currently is to click the x button.

**Comment by TakaOtaku** [comment]
I have to see how to implement it correctly.
At the moment the modals are controlled by primeng, so I have to fiddle a bit.
