### ISSUE TITLE
Feature Request: Show the number of cards in a collection in the card detail modal

### ISSUE THREAD

**Issue by dartanian300** [TakaOtaku/Digimon-Card-App#460]
When building a deck it's useful to only add the number of cards you own. Currently the only way to see the number of cards in your collection is to toggle the "Collection Mode". It would be nice to see this number in the card details modal as well.

**Comment by TakaOtaku** [comment]
The first part here is intended, ad most users don't track their collection.
The second part can be added, but I will add it as a setting. That way it won't show for people that don't want it.

**Comment by TakaOtaku** [comment]
Already added :)
