### ISSUE TITLE
Deck metrics are hidden when card view is open

### ISSUE THREAD

**Issue by dartanian300** [TakaOtaku/Digimon-Card-App#461]
When in the deck builder, 2/3 of the deck stats are hidden when the card view is open. This is the default view when going to the deck builder and the button to hide the card view is very easy to miss. I personally have built 3 decks and missed it every time. 

<img width="1554" alt="Screen Shot 2023-01-06 at 1 57 53 PM" src="https://user-images.githubusercontent.com/3358537/211081834-983aabb8-84b6-4288-b1ff-7822902775c6.png">
<img width="1551" alt="Screen Shot 2023-01-06 at 1 57 43 PM" src="https://user-images.githubusercontent.com/3358537/211081810-73072569-b6c6-4722-8922-aeb989aa9b38.png">

It would be nice to show all metrics even when the card view is open. Having to toggle the view on/off is a little annoying.

**Comment by TakaOtaku** [comment]
Not really sure about that, I would have to make a toggle to switch between 1/2/3 stats etc.
With the stats to big in the first screen, I did get quite a bit of complaints that it is to full.
