### ISSUE TITLE
Forward/Back buttons in card modal don't work for decks

### ISSUE THREAD

**Issue by dartanian300** [TakaOtaku/Digimon-Card-App#462]
The next/previous buttons in the card detail modal don't work as expected in the deck builder. When opening the modal via deck cards, the buttons do not show the next/previous cards in the deck. Instead, they show the card with the next card number (example: viewing ST7-01 and clicking next shows ST7-02). Sometimes the buttons don't work at all.

Additionally, the modal remembers the last card it showed.
Steps to reproduce:

1. Create a deck with ST7-01
2. Open the card modal on the deck side of the page using ST7-01
3. Click the next button to view ST7-02
4. Close the modal
7. Open the modal again
8. This modal will be showing ST7-02 instead of ST7-01 since it was showing ST7-02 when it was closed.

<img width="757" alt="Screen Shot 2023-01-06 at 2 04 21 PM" src="https://user-images.githubusercontent.com/3358537/211083238-de32241f-506a-45f5-adb0-46d57519156a.png">

**Comment by TakaOtaku** [comment]
Yeah, that is true, I did take the easy way for that implementation.
