### ISSUE TITLE
[Feature Request] Export to Untap

### ISSUE THREAD

**Issue by 4fieldbox** [TakaOtaku/Digimon-Card-App#463]
I mainly play on Untap (when not in person), would it be possible to add Untap to the list of export options? For reference, you can do this on digimoncard.dev, and this appears to be the format: 1 MetalGreymon (DCG) (BT1-114)

Love the site, by far the best deck building site

**Comment by TakaOtaku** [comment]
I haven't added it yet, as nobody seemed to care :) 
It seems pretty easy to add, so I should be able to add it by tomorrow.

Thanks for liking and using the site!

**Comment by 4fieldbox** [comment]
Awesome, thanks 👍

**Comment by chardin1** [comment]
Here's the documentation for the format: https://wiki.untap.in/books/deck/page/import-from-text

The one @4fieldbox mentioned isn't listed so we'd need to test that.

**Comment by dartanian300** [comment]
Here's the documentation for the format: https://wiki.untap.in/books/deck/page/import-from-text

The one @4fieldbox mentioned isn't listed so we'd need to test that.

**Comment by 4fieldbox** [comment]
New feature works. Thanks 👍

**Comment by dartanian300** [comment]
@4fieldbox nothing has been implemented yet. I was just posting Untap's documentation for @TakaOtaku

**Comment by 4fieldbox** [comment]
TakeOtaku must have already done it based on my suggestion because it is indeed implemented. Sorry for the confusion 👍

**Comment by TakaOtaku** [comment]
Yeah I added it yesterday and forgot to comment :D 
I am not sure if it works, as I have never played with untap yet and wanted to try it today xD

**Comment by 4fieldbox** [comment]
Is it possible to have the DCG in square brackets?

Did you give Untap a try, thoughts?

Thanks

**Comment by TakaOtaku** [comment]
Ohh yeah, I forgot.
I added it the same day you wrote and tried untap a bit and it is quite good :)
