### ISSUE TITLE
BT12-109 Incorrect translation

### ISSUE THREAD

**Issue by SoenL** [TakaOtaku/Digimon-Card-App#467]
BT12-109 Overflowing Power has an incorrect translation in its text.
Per the wiki https://digimoncardgame.fandom.com/wiki/BT12-109
![BT12-109_116fa7en-US](https://user-images.githubusercontent.com/122897090/212933889-6f133bfb-3af6-4923-a8fe-60f57441aa64.png)

**Comment by TakaOtaku** [comment]
Should be fixed :)
