### ISSUE TITLE
In Collection Mode, Alternate Arts with 0 quantity are not greyed out

### ISSUE THREAD

**Issue by epicdang** [TakaOtaku/Digimon-Card-App#471]
Regular arts are greyed out at 0 quantity, but alternate arts are not.  For example:

![Screenshot 2023-02-08 8 11 50 PM](https://user-images.githubusercontent.com/8013905/217689225-1d977ca1-d15a-481c-be94-bd8e2e8fc2fd.png)

**Comment by TakaOtaku** [comment]
Check your settings, you can set how many NAs and AAs you want to collect.
Since the last update, the AAs collection threshold can be set differently and as a default is set to 0.

**Comment by epicdang** [comment]
Oh my apologies, thank you so much!
