### ISSUE TITLE
Missing / Incorrect Tags and Cards

### ISSUE THREAD

**Issue by Purpl-Peach** [TakaOtaku/Digimon-Card-App#479]
While putting my collection in the site I noticed a couple of small things which I've listed below.

- Lillymon EX1-039, Agumon ST1-03, Numemon BT2-056, Gammamon BT8-008, Terriermon EX2-025 are all improperly tagged as alt-art 
- Silphymon BT8-015 is tagged as Red and Green while all stamped variants of Paildramon ST9-05 aren't tagged with any color 
- Both versions of The Ray of Victory BT2-096 are missing the uncommon tag
- "Reinforcement Plug-In O" BT10-109 is misnamed "Upgrade Plug-In O"
- The english alternate art versions of WarGrowlmon EX2-010, Taomon EX2-023, and Rapidmon EX2-027 from Tamer Party Vol. 6 are missing

**Comment by Purpl-Peach** [comment]
I have links to images of the cards listed above if needed.
- [WarGrowlmon EX2-010](https://static.wikia.nocookie.net/digimoncardgame/images/3/3b/EX2-010.png/revision/latest)
- [Taomon EX2-023](https://static.wikia.nocookie.net/digimoncardgame/images/0/09/EX2-023.png/revision/latest)
- [Rapidmon EX2-027](https://static.wikia.nocookie.net/digimoncardgame/images/9/95/EX2-027.png/revision/latest)

**Comment by herculess89** [comment]
Also i found that:
ST8-08 is missing (sec attack +1) keyword tag.
ST9-07 is missing blocker keyword tag.
BT11-076 is wrongly tagged as having DigiXros special requirement.

**Comment by TakaOtaku** [comment]
Thanks guys, just added all the missing stuff and fixed the errors <3
