### ISSUE TITLE
Search bar responsiveness 

### ISSUE THREAD

**Issue by lupoDharkael** [TakaOtaku/Digimon-Card-App#481]
Typing in the search bar in order to filter cards by name feels sluggish and takes a lot of time filtering cards while you haven't finished writing the complete word. It is specially notable if you type fast. I think adding a filter delay of 200 or 300ms that gets reset with input would help make it feel less heavy and would eliminate some unneeded filtering.

**Comment by TakaOtaku** [comment]
Yeah, that annoyed me for a while, but I am honest, I was just too lazy to fix it.

I have added a debounce timer for the input of text and to about half of the other filters.

The change should be live in a few minutes and the rest of the rework should come in a bit :)
