### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by lupoDharkael** [TakaOtaku/Digimon-Card-App#482]
As per [Github docs](
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

I know the readme states that you can contribute to the project but it would be better if the project had a proper license so the content and the contributions offer explicit permissions and it doesn't fall under legal grey areas.

Feel free to close this issue as I understand it may feel low priority or unneeded for the actual project.

**Comment by TakaOtaku** [comment]
Hey, I didn't really spend much time looking into it, because I thought it wasn't that necessary.
I added an MIT license, which I found after a quick look.
thanks :)
