### ISSUE TITLE
Collection and Deck data repeatedly being erased

### ISSUE THREAD

**Issue by EllyCait** [TakaOtaku/Digimon-Card-App#490]
Multiple times now all of the decks I've built and cards I've added to my collection have been erased, often a matter of days after creating and saving them.

When this happens, links to those decks I've created stop working.

**Comment by TakaOtaku** [comment]
Hey did you login with an Google Account? 
If you have they will be saved there and if you don't they will be saved in your browser, which will be deleted, when you clear your browsers data.

**Comment by EllyCait** [comment]
I have been logging in with a Google account, yes.

The only thing I can think of is maybe something with the firewalls and filters at my job (I sometimes open the site on a break) is messing with that function and causing it to be erased from my Google account if I log in there?

But that shouldn't have been the case at minimum the first time that happened as they'd previously been there when I checked them with my phone the day before, which was at home.

**Comment by TakaOtaku** [comment]
Thanks for the reply, can you send my your profile link?
Should look something like this: https://digimoncard.app/user/S3rWXPtCYRN8vSrxY3qE6aeewy43

The last part there is your user-id and with that I can take a look at my database and maybe find out more :)

**Comment by TakaOtaku** [comment]
I have remodeled the Login Process and such, it should still look the same but work a bit different in the back.
Hopefully this is fixed with that.

**Comment by TakaOtaku** [comment]
Should be fixed, if otherwise please reopen the ticket. :)
