### ISSUE TITLE
My deck view doesn't scale correctly and doesn't have scroll bar

### ISSUE THREAD

**Issue by Tamska** [TakaOtaku/Digimon-Card-App#491]
My resolution is 2560 x 1600

and on my screen when I am looking at my decks it looks like this, without any scroll bar etc. 

![image](https://github.com/TakaOtaku/Digimon-Card-App/assets/117350320/4a5ca8bb-bc08-41b5-9af2-4d07aca9cdbc)

**Comment by TakaOtaku** [comment]
I'll try to fix it as soon as possible. For now, you could switch to the other deck view in the settings, while I fix it.
