### ISSUE TITLE
Alternate Art Cards will not be imported

### ISSUE THREAD

**Issue by Neltheraku** [TakaOtaku/Digimon-Card-App#495]
If a card with an alternative art is exported, it will be provided with the respective character at the end, for example BT5-001_P1. When importing the cards, no alternative art is recognized and therefore does not appear in the Deck. For example if I try to import BT5-001_P1 no card will be added to my deck. Regular cards like BT5-001 work perfectly when importing.

**Comment by TakaOtaku** [comment]
Ohh yeah that is my mistake, I do some verification and I check if the part behind "-" is a number, but with an AA it isnt a number anymore.
I try to add the correct check soon :)
