### ISSUE TITLE
Import and Export icon 

### ISSUE THREAD

**Issue by lupoDharkael** [TakaOtaku/Digimon-Card-App#498]
I know this might be subjective but I'm sharing it because 2 friends already commented this and that was also my personal thought.
![image](https://github.com/TakaOtaku/Digimon-Card-App/assets/14951430/3265de31-d98f-4054-af24-cc335ccd4826)

The import and export button icons feel inverted, the import button is represented by an arrow getting out of something and feels like it means data coming out and the other way around for the export button.

I propose exchanging the icons for the buttons.

**Comment by TakaOtaku** [comment]
Yeah, thats something that can be seen as import and Export.
I can Switch it and wait for reactions 😁
