### ISSUE TITLE
New deck buttom not clearing internal deck data

### ISSUE THREAD

**Issue by lupoDharkael** [TakaOtaku/Digimon-Card-App#499]
The "new deck" button does not properly remove the data from the previous deck being edited.

Steps to reproduce:

1.  Open a deck saved in "Profile

![image](https://github.com/TakaOtaku/Digimon-Card-App/assets/14951430/741e0314-b1bd-4cce-b9e0-54d1f171e840)

2. Clear the contents with the New Deck button

![image](https://github.com/TakaOtaku/Digimon-Card-App/assets/14951430/9dde3154-56c1-4ffd-aa86-068eea626ae7)

3. Import another deck from text

![image](https://github.com/TakaOtaku/Digimon-Card-App/assets/14951430/bef0dd77-8be3-49cf-80ad-5f1fbbd91e1b)

Now both decks appear at the same time and sometimes you can even see some cards not belonging to either the old or the new:

![image](https://github.com/TakaOtaku/Digimon-Card-App/assets/14951430/38e4bc26-87c9-4ea5-bf3f-2f4b5315c326)

**Comment by TakaOtaku** [comment]
Yeah thats a bug I am currently attempting to fix, but thanks for the report 😁
