### ISSUE TITLE
No Available AA or Stamped cards etc.

### ISSUE THREAD

**Issue by StudentYaw** [TakaOtaku/Digimon-Card-App#506]
Ever since the rollback today only normal artworks are available and some previously missing alt arts (for example Gabumon tournament pack 9) 
The Filter option work properly but I can no longer display both languages at the same time

Is this intended?

**Comment by TakaOtaku** [comment]
The Language Option now always displays all cards, but english takes english images if possible and japanese takes japanese images.

![image](https://github.com/TakaOtaku/Digimon-Card-App/assets/9803280/ad1228fd-6c20-46be-b19a-dacae1e30fb3)
What AAs are you not finding? The Gabumon AAs should all be here?

**Comment by StudentYaw** [comment]
![IMG_1955](https://github.com/TakaOtaku/Digimon-Card-App/assets/126025036/43a796b0-fae4-41f6-84b5-dff431d0967c)
I can’t find any prerelease cards , stamped cards or box topper or AA of anything else besides what’s post in this picture

**Comment by TakaOtaku** [comment]
My cache was the mistake. It should be fixed in a few minutes. 
Thanks for reporting the problem.

**Comment by StudentYaw** [comment]
Just a quick note: On Desktop the problem is fixed but on mobile devices not
Any idea?

**Comment by TakaOtaku** [comment]
Should just be something with the cache, either clear it or wait a bit. The cache is cleared after X time on browsers :)
