### ISSUE TITLE
Bug Report: Collection is setting my card to Quantity 6x

### ISSUE THREAD

**Issue by demonku78** [TakaOtaku/Digimon-Card-App#508]
When I'm searching throw my Collection or Deck Building.  The first card in the search just gets set to 6x quanitity.  Seems to only be happening whenever I filter by "1 owned card in collection" 

It seems like when it's not filtered, it makes the 2nd card in the list 6x quanitity without me adding it at all.

**Comment by TakaOtaku** [comment]
Could you send me a Screenshot from your filter settings?
I cant seem to reproduce the error
