### ISSUE TITLE
Can't add specific cards to decks

### ISSUE THREAD

**Issue by jeff-wichers** [TakaOtaku/Digimon-Card-App#509]
I've run into a few issues adding specific cards to decks in the deckbuilder. I'm using the latest versions of Chrome on Windows 10 and Android 13. Card View shows them as being in the deck, but they're not in the deck view. When it's saved, they no longer show as being in the deck in the Card View. 
![image](https://github.com/TakaOtaku/Digimon-Card-App/assets/3453707/0db8a3af-e88f-4ad2-b505-7fb6872b4d59)

- Phascomon ST14-04
- ADR-02 Searcher EX2-046
- ADR-03 Pendulum Feet EX2-047
- ADR-04 Bubbles EX2-048
- ADR-01 Jeri EX2-049
- ADR-05 Creep Hands EX2-050
- ADR-07 Palates Head EX2-051
- ADR-09 Gatekeeper EX2-054
- Reaper EX2-055

**Comment by TakaOtaku** [comment]
Should be fixed with the next Update
