### ISSUE TITLE
Can't add ST14-04 Phascomon to deck

### ISSUE THREAD

**Issue by peachyspike** [TakaOtaku/Digimon-Card-App#512]
Attempted on iOS and on PC (firefox). attempting to add ST14-04 to deck causes counter to add on the collection view, but not in deck view; refreshing resets the counter on collection view - ST14-04 was still not added to the deck.
On PC, its more obvious that there is some issue with adding ST14-04 to the deck, since it looks like the deck is getting a new card (the cards attempt to move to slot in the new item) but it suddenly disappears and deck reverts to phascomon-less state.

**Comment by TakaOtaku** [comment]
Should be fixed in the next update, the card didn't have a level on the wiki, so my deck builder didn't recognize it as a valid card.
