### ISSUE TITLE
When setting images for decks, shows [object Object] instead of name of card

### ISSUE THREAD

**Issue by Yatotoro** [TakaOtaku/Digimon-Card-App#515]
![2023-10-16 21_42_32-Digimon Card Game - Profil — LibreWolf](https://github.com/TakaOtaku/Digimon-Card-App/assets/41319299/031cdcd1-f152-4d2e-8ecb-dd452788a74f)

**Comment by TakaOtaku** [comment]
Is fixed, thank you for the report :) 
(Release for the Update will take a few minutes)
