### ISSUE TITLE
Can't open decks on page 2 of profile

### ISSUE THREAD

**Issue by jeff-wichers** [TakaOtaku/Digimon-Card-App#528]
When I click on decks on the second page of my profile on the desktop site, they do not open. Mobile works fine.

**Comment by jeff-wichers** [comment]
Looks like I had an empty deck on the second page and that caused weird behavior. Was able to delete the deck in the mobile version and now the desktop version works as expected.

**Comment by TakaOtaku** [comment]
Ohh, that shouldn't happen. 
Was it just a deck without name and cards, that caused the issue?
It shouldn't be hard to stop it from happening again :)

**Comment by jeff-wichers** [comment]
Yep. No names and no cards.

**Comment by TakaOtaku** [comment]
Fixed with todays update :)
