### ISSUE TITLE
Cards disappear when I try to increase their amount

### ISSUE THREAD

**Issue by Ralkias** [TakaOtaku/Digimon-Card-App#531]
I've tried increasing the amount of some cards that I have in my collection. But when I pressed the + button in collection mode, instead of the number increasing, the card just.. disappeared. Not just out of my collection, but apparently from the account. 
When I look for them in the searchbar, there are no results. When I scroll down to look for them manually, or if I filter for them, the cards are just not there. Not even alternate forms. 
This issue is new to me, as everything worked perfectly up until today. It isn't an issue with every card either. Some still work normally, others are deleted whenever I try it.
I tried restarting my device, swapping the browser, swapping the device, relogging, trying a different internet access - the cards are still non-existant.

They do exist on other accounts, and I can increase the amount of cards there without an issue. But with my account, it just deletes the cards when I try.

**Comment by TakaOtaku** [comment]
Another helpful thing would be if you press F12 and open the console like in the image:
![image](https://github.com/TakaOtaku/Digimon-Card-App/assets/9803280/cb9ba872-ff2f-4be6-b41a-5fb624cd2e35)

If you then see a red message in the console, you could post a screenshot here.

Sorry for the trouble

**Comment by TakaOtaku** [comment]
Thank you I am gonna check it out and see whats wrong :)

**Comment by Ralkias** [comment]
Nope, the issue still remains. But it really seems to be a problem with the amount of cards, because they vanish as soon as I try to increase it beyond 5.  Anything below that is not an issue.

**Comment by TakaOtaku** [comment]
Then it could be a filter issue, could you open the settings change Collection Filter Max to any number 5 should be the default and then save setting.
I was just able to replicate it by removing the Collection Filter Max Number and saving the settings, then if you go over 5 it just gets filtered out.

**Comment by TakaOtaku** [comment]
Gonna work on a correct fix right away though.

**Comment by Ralkias** [comment]
> Then it could be a filter issue, could you open the settings change Collection Filter Max to any number 5 should be the default and then save setting. I was just able to replicate it by removing the Collection Filter Max Number and saving the settings, then if you go over 5 it just gets filtered out.

I changed deleted the number (5), saved, typed in 5 again, saved - and now they are all back. I don't know how, but everything works fine now. Thanks for the help :)

**Comment by TakaOtaku** [comment]
Okay great, thanks for reporting the error :D
I also have pushed a permanent fix so that it won't repeat, if you have another bug or feature just open an Issue i will try to add it :D
