### ISSUE TITLE
Collection Mode Toggle resets filters

### ISSUE THREAD

**Issue by jeff-wichers** [TakaOtaku/Digimon-Card-App#532]
On Desktop, when I toggle the Collection Mode toggle, the cards displayed are reset to the unfiltered results.

**Comment by TakaOtaku** [comment]
Ohh yeah, that needs to be fixed asap. Gonna push a change in a bit.

**Comment by TakaOtaku** [comment]
Just fixed it and it should work live in a few minutes.

**Comment by jeff-wichers** [comment]
Toggle is working correctly for me again. Thanks for the quick fix.
