### ISSUE TITLE
Some card corrections

### ISSUE THREAD

**Issue by herculess89** [TakaOtaku/Digimon-Card-App#539]
BT1-009 Alt-Art is tagged as Foil
BT3-057 Tagged as Ultimate  instead of Mega
BT9-050 Tagged as Mega instead of Champion
BT10-101 Normal art is the non-errata
EX4-028 Is SR instead of U

**Comment by herculess89** [comment]
The cards are still with errors.

**Comment by tari101190** [comment]
The update hasn't gone live yet, but they've been corrected.
