### ISSUE TITLE
Missing Cards BT17

### ISSUE THREAD

**Issue by Neltheraku** [TakaOtaku/Digimon-Card-App#542]
BT17 was released in japanese on March 29, 2024 and will be released in english on August 9, 2024. Yet there are still cards missing in the app.

Growlmon (BT17-010)
Pulsemon (BT17-030)

**Comment by herculess89** [comment]
![Screenshot 2024-06-30 175853](https://github.com/TakaOtaku/Digimon-Card-App/assets/86571930/82518eca-7e54-49da-8e71-cad1e9b309da)
The cards are there for me. Maybe you filtered them out.

**Comment by Neltheraku** [comment]
I can see them now too. I swear to god they were missing when I looked them up. I'll close the issue
