### ISSUE TITLE
[Feature Request] Sort cards by level in image export

### ISSUE THREAD

**Issue by Nogooduser** [TakaOtaku/Digimon-Card-App#543]
I really love the interface of digimoncard.app but one thing that's always bugged me compared to other similar sites is that in the image export cards are always ordered very randomly.

This is not how I believe most people prefer viewing a deck profile because, for example, if I want to check all the level 6 digimon in a deck, with the way digimoncard.app sorts them in the image they might be in different places, which makes the viewing experience not ideal.

In my humble opinion, I believe the image export should sort cards by level first rather than set, followed at the end by options and tamers (or vice versa)

So, if this suggestion was implemented, the cards would be displayed from left to right in this order: level 2 (eggs), level 3, level 4, level 5, level 6, level 7, options, tamers (or tamers > options. either is fine)

Within each level/category they could be sorted by set and set number, but other than that I truly believe that sorting the cards like this in the image will provide the best experience for sharing and viewing decks.

This is even how the deck builder already sorts them, so it's not like it wasn't implemented before, it just doesn't get applied in the image export currently, and I really think it should.

Thank you for your consideration regardless.

**Comment by not-tomo** [comment]
Not the maintainer, but a pull request that was just merged yesterday, #540, tackled this very issue by sorting the cards by level before image exports! Those changes are now up on the website, so I encourage you to see if they sufficiently address your concerns.

**Comment by Nogooduser** [comment]
Well that's some timing! Yes that PR fixes the exact issue I had so I'll be closing this issue. Thank you so much for implementing this fix.
