### ISSUE TITLE
EX2-007 effect is missing from your site

### ISSUE THREAD

**Issue by tari101190** [TakaOtaku/Digimon-Card-App#8]
EX2-007 effect is missing from your site. It is listed on the official en.digimoncard.com site.

![image](https://user-images.githubusercontent.com/104586582/166163079-37906ae8-3ddf-4757-b185-fabf785fcc36.png)
![image](https://user-images.githubusercontent.com/104586582/166163087-37c657e9-cbea-46cb-b296-a42307e4b084.png)

**Comment by TakaOtaku** [comment]
Fixed!
